# Generated by Django 2.2.10 on 2021-09-15 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customersdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unpaid_amount', models.IntegerField(auto_created=True, default=0)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('rates', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_sale_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('total_value', models.IntegerField(blank=True, default=0, null=True)),
                ('total_paid_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('cust_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='milk_CRM.Customersdata')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_relation_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cust_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='milk_CRM.Customersdata')),
            ],
        ),
    ]
