# Generated by Django 3.2.7 on 2021-09-16 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milk_CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_relation_data',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk_CRM.customersdata'),
        ),
        migrations.AlterField(
            model_name='customer_sale_data',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk_CRM.customersdata'),
        ),
        migrations.CreateModel(
            name='Milk_transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rates', models.IntegerField(default=50)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk_CRM.customer_sale_data')),
            ],
        ),
    ]
