# Generated by Django 3.2.7 on 2021-09-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_CRM', '0002_auto_20210916_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milk_transaction',
            name='customer',
            field=models.CharField(choices=[('Himanshu', 'Himanshu'), ('check', 'check'), ('check1', 'check1'), ('2nd element', '2nd element')], max_length=20),
        ),
    ]
