# Generated by Django 3.2.7 on 2021-09-16 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milk_CRM', '0004_auto_20210916_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='milk_transaction',
            name='cust_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='milk_CRM.customer_sale_data'),
        ),
        migrations.AlterField(
            model_name='milk_transaction',
            name='customer',
            field=models.CharField(choices=[('Himanshu', 'Himanshu'), ('check', 'check'), ('check1', 'check1'), ('2nd element', '2nd element'), ('latest', 'latest'), ('trynew', 'trynew')], max_length=20),
        ),
    ]
