# Generated by Django 3.2.7 on 2021-09-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_CRM', '0005_auto_20210916_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_sale_data',
            name='unpaid_amount',
            field=models.IntegerField(auto_created=True, default=0),
        ),
        migrations.AlterField(
            model_name='milk_transaction',
            name='customer',
            field=models.CharField(choices=[('Himanshu', 'Himanshu'), ('check', 'check'), ('check1', 'check1'), ('2nd element', '2nd element'), ('latest', 'latest'), ('trynew', 'trynew'), ('Harshit', 'Harshit')], max_length=20),
        ),
    ]
