# Generated by Django 3.2.7 on 2021-09-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_CRM', '0006_auto_20210916_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_sale_data',
            name='unpaid_amount',
            field=models.IntegerField(default=0),
        ),
    ]
