# Generated by Django 3.2.7 on 2021-09-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_CRM', '0009_payment_transactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment_transactions',
            new_name='Payment_transact',
        ),
    ]
