# Generated by Django 3.2.7 on 2021-09-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_CRM', '0010_rename_payment_transactions_payment_transact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milk_transaction',
            name='customer',
            field=models.CharField(choices=[('Himanshu', 'Himanshu')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment_transact',
            name='customer',
            field=models.CharField(choices=[('Himanshu', 'Himanshu')], max_length=20),
        ),
    ]
