# Generated by Django 3.2.7 on 2021-09-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_CRM', '0011_auto_20210916_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milk_transaction',
            name='customer',
            field=models.CharField(choices=[('Himanshu', 'Himanshu'), ('Kamal', 'Kamal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment_transact',
            name='customer',
            field=models.CharField(choices=[('Himanshu', 'Himanshu'), ('Kamal', 'Kamal')], max_length=20),
        ),
    ]
