# Generated by Django 3.2.7 on 2021-09-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_CRM', '0013_auto_20210916_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milk_transaction',
            name='customer1',
        ),
        migrations.AlterField(
            model_name='milk_transaction',
            name='customer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
