# Generated by Django 3.2.7 on 2021-09-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_CRM', '0014_auto_20210916_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_transact',
            name='customer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
